### ISSUE TITLE
[ERROR] keyword file has incorrect format or belongs to a different platform [ERROR] loading keyword file at '~/alexa_linux.ppn' failed with 'INVALID_ARGUMENT'

### ISSUE THREAD

**Issue by pooneh-nb** [shivasiddharth/avs-device-sdk-pi#1]
Hey shivasiddharth,
Thanks for sharing this project. I've installed Alexa SDK on Linux, ubuntu. Instead of getting alexa_rasberry-pi.ppn I download alexa_linux.ppn, however, I get this error:
[ERROR] keyword file has incorrect format or belongs to a different platform
[ERROR] loading keyword file at '/home/c2/alexa/source/voice-assistant-central/avs-sdk-changes/alexa_linux.ppn' failed with 'INVALID_ARGUMENT'
Any thought on this? Should I change anything in alexa_picovoice_trigger.py?

**Comment by pooneh-nb** [comment]
Hey shivasiddharth,
Thanks for sharing with us this project. I've installed Alexa SDK on Linux, ubuntu. Instead of getting alexa_rasberry-pi.ppn I download alexa_linux.ppn, however, I get this error:
[ERROR] keyword file has incorrect format or belongs to a different platform
[ERROR] loading keyword file at '/home/c2/alexa/source/voice-assistant-central/avs-sdk-changes/alexa_linux.ppn' failed with 'INVALID_ARGUMENT'
Any thought on this? Should I change anything in alexa_picovoice_trigger.py?

**Comment by shivasiddharth** [comment]
Still the ppn has to be alexa_rasberry-pi.ppn only. alexa_linux.ppn will be x86 linux ppn.

**Comment by pooneh-nb** [comment]
I'm getting the same error with alexa_rasberry-pi.ppn

**Comment by shivasiddharth** [comment]
I prefer to look at the terminal output that you are getting. If the keyword_path is not working, just use `--keywords alexa` instead of --keywords

**Comment by pooneh-nb** [comment]
ok, I have a good update. I made the change you suggested. But we don't need to keyword_path anymore we just need to write out 'alexa'. Here is my command:
python3 ~/alexa_picovoice_trigger.py --access_key ${ACCESS_KEY} --keywords 'alexa'
Thanks shivasiddharth!
