### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by alsacian** [shivasiddharth/avs-device-sdk-pi#2]
Hello, I get this error when I run the script, key and wake word are OK
Traceback (most recent call last):
  File "/home/pi/avs-device-sdk-pi/Alexa/alexa_picovoice_trigger.py", line 214, in <module>
    main()
  File "/home/pi/avs-device-sdk-pi/Alexa/alexa_picovoice_trigger.py", line 210, in main
    input_device_index=args.audio_device_index).run()
  File "/home/pi/avs-device-sdk-pi/Alexa/alexa_picovoice_trigger.py", line 72, in run
    s.connect(('localhost', SOCKET_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Thanks

**Comment by shivasiddharth** [comment]
Why are you using those scripts? Those are there for my developmental purposes. Use only what is there in the scripts/master branch.

**Comment by shivasiddharth** [comment]
The YouTube is re-directing to a wrong branch of the Git. I have fixed the link in YouTube. This is what you need to follow: https://github.com/shivasiddharth/avs-device-sdk-pi Use this file: https://github.com/shivasiddharth/avs-device-sdk-pi/blob/scripts/alexa_picovoice_trigger.py

**Comment by alsacian** [comment]
Ok, thanks for your good work on this project, I still use Google
assistant, more easy to play with 😄
I worked a little bit with your new code, websocket message seems promising,
I can't get connection working properly yet, sometimes no problem.
Best regards

Le jeu. 24 févr. 2022 à 15:27, shivasiddharth ***@***.***> a
écrit :

**Comment by shivasiddharth** [comment]
I am no expert with C or C++ had it been python I could have got it to work. Amazon guys are a closed group, they do only what they think is right. They may or may not integrate Porcupine within the Alexa. We need to wait and see. Honestly, Google Assistant SDK for Pi is dying. There has not been significant updates to the code base. To give you an idea of what's happening, the SDK does not  work with certain newer modules/packages and older modules do not work with newer OS releases. It is becoming a nightmare for me to maintain it.

**Comment by alsacian** [comment]
Ok, thanks, I don't like this too, nether ending updates and breaking
changes....
They want we buy their products for sure. I bought 1 echo 4 in France for
only 50 € last Christmas. Sure it's not funny without tinkering 😄
Best regards


Le ven. 25 févr. 2022 à 11:05, shivasiddharth ***@***.***> a
écrit :
