### ISSUE TITLE
"subprocess.call failed" sometimes in "alexa_picovoice_trigger.py"

### ISSUE THREAD

**Issue by rchobby-net** [shivasiddharth/avs-device-sdk-pi#4]
Hello,
your script works really well. However, after restarting the pi, I often have the problem that the ID of the terminal window changes and then the script does not work. I then have to manually enter the new ID for the "subprocess.call" in the "alexa_picovoice_trigger.py" file. Do you have a solution for this problem that the new id is automatically detected and entered into the "alexa_picovoice_trigger.py" file?
Thanks again

**Comment by shivasiddharth** [comment]
There is no way to do that automatically.
