### ISSUE TITLE
I have 2 problemes

### ISSUE THREAD

**Issue by theos10** [shivasiddharth/avs-device-sdk-pi#5]
Hi,
I have 2 problème in my raspberry pi without grafic interface : 
wmctrl -l
Cannot open display.
python3 alexa_picovoice_trigger.py --access_key xxxx --keyword_paths /home/pi/avs-device-sdk-pi/alexa_raspberry-pi.ppn
Traceback (most recent call last):
  File "alexa_picovoice_trigger.py", line 210, in <module>
    main()
  File "alexa_picovoice_trigger.py", line 206, in main
    input_device_index=args.audio_device_index).run()
  File "alexa_picovoice_trigger.py", line 89, in run
    sensitivities=self._sensitivities)
TypeError: create() got an unexpected keyword argument 'access_key'

thank for your help.

**Comment by shivasiddharth** [comment]
Assistants are meant to be run only on Desktop version of Raspberry Pi OS. They will not work on Raspberry Pi OS Lite.
