### ISSUE TITLE
No module named 'pvporcupine'

### ISSUE THREAD

**Issue by Mambo-beep** [shivasiddharth/avs-device-sdk-pi#6]
Hi,
i installed all of the modules correctly and without any errors, but when i start the script, this error message appears: 

```
sudo python3 /home/pi/alexa_picovoice_trigger.py --access_key $k6GpIxhfnqIM7w1yDkxGO5ybGcPx9kRA6GkjwzR/evkDICMw713jEw== --keyword_paths $/home/pi/alexa_raspberry-pi.ppn
Traceback (most recent call last):
  File "/home/pi/alexa_picovoice_trigger.py", line 20, in <module>
    import pvporcupine
ModuleNotFoundError: No module named 'pvporcupine'
```
Can someone help me with this?

**Comment by shivasiddharth** [comment]
Please check the command that I have given. `sudo python3` is not the same as `python3`

**Comment by Mambo-beep** [comment]
But without sudo it don't find the .ppn file!

**Comment by shivasiddharth** [comment]
Sudo has nothing to do with the ppn file path. Why do you have a $ in the path string ? Check the command syntax that I have given

**Comment by Mambo-beep** [comment]
Thank you.... I've didn't saw that.
