### ISSUE TITLE
Sensitivity changing 

### ISSUE THREAD

**Issue by Mambo-beep** [shivasiddharth/avs-device-sdk-pi#7]
Hi,
I've tried to set the sensitivity of the trigger word on a higher level in the script, but when I run there's a error message? How can I change it correctly? Also in my web research there's nothing to find about the sensitivity parameter.

Thank you for the Help and an great evening!

**Comment by shivasiddharth** [comment]
It means that you have not set the sensitivity properly. Share a screenshot of the part where you have set the sensitivity.

**Comment by pillowtoaster** [comment]
Sorry for my long inactivitie. I've tried to change the sensitivity in this part of the script:
"""
        Constructor.

        :param library_path: Absolute path to Porcupine's dynamic library.
        :param model_path: Absolute path to the file containing model parameters.
        :param keyword_paths: Absolute paths to keyword model files.
        :param sensitivities: Sensitivities for detecting keywords. Each value should be a number within [0, 1]. A
        higher sensitivity results in fewer misses at the cost of increasing the false alarm rate. If not set 0.5 will
        be used.
        :param input_device_index: Optional argument. If provided, audio is recorded from this input device. Otherwise,
        the default audio input device is used.
        :param output_path: If provided recorded audio will be stored in this location at the end of the run.
        """
``
But i dont now how the command have to look like. All what i've tried ended in an error message.

**Comment by shivasiddharth** [comment]
I asked for a screenshot of the part where you have set the sensitivity.

**Comment by pillowtoaster** [comment]
I cant give you an schreenshot, because i dont now the command!

**Comment by pillowtoaster** [comment]
I've fixed it!
